### ISSUE TITLE
'cell label should not contain 0'? meaning

### ISSUE THREAD

**Issue by paulyashna** [saezlab/liana#12]
Hi Daniel,  Will you have an idea why I keep getting an error 'cell label should not contain 0' error with any of the methods I try with the liana wrapper function. I understand the metadata information is directly taken from the seurat object. I have added cluster annotations under the column seurat_annotations in the metadata, and still get this error. I appreciate any help on this.

**Comment by dbdimitrov** [comment]
Hi Yashna,

I haven't encountered that error.

Throwing a shot in the dark here, but I tried passing integers (including 0) as the name of cluster (assuming this was the issue) and I did not get an error since LIANA will convert ints to factor.

You should get something like:
`Squidpy: seurat_annotations was converted to factor` if this is the case.

One thing could work would be to just re-install the R package for liana (i.e. run this alone:
`Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS = TRUE) # ignore warning from iTALK
devtools::install_github('saezlab/liana')`

I only made this change recently, so maybe your version does not include it.

I hope that helps.

Daniel

**Comment by paulyashna** [comment]
Hi Daniel,

The Idents(seurat_object) in my case was numeric and cellchat from LIANA does not accept a '0' as identity of a cluster. I was able to correct this and run cellchat with LIANA. Also, 'connectome' works now and does not fall into an infinite loop as before. Thanks for your quick responses.

Best Regards,
Yashna

**Comment by dbdimitrov** [comment]
Hi Yashna,

Oh okay, my bad, I automatically thought of Squidpy, as there was a similar issue there.
I will have a look at CellChat too and will provide an update!

Thanks,
Daniel

**Comment by dbdimitrov** [comment]
Hi Yashna, 

Actually I checked running CellChat with clusters starting from 0 (defined as doubles), but for me it worked.

Don't hesitate to post any further issues.

Regards,
Daniel
