### ISSUE TITLE
Running Liana on Mouse single cell

### ISSUE THREAD

**Issue by PolSabt** [saezlab/liana#135]
Hi !
Thanks a lot for this package.

The tutorial when well, but I wanted to use it on a murin Seurat Object, not error came out of the Run part but the following code: 

```{r liana_run, message = FALSE, print = FALSE, results='hide'}
# Run liana
testdata=MyseuratObject
liana_test <- liana_wrap(testdata)

# Liana returns a list of results, each element of which corresponds to a method
liana_test %>% dplyr::glimpse()
```
Give me a weird [ligands / receptors] information F10/F3 .... instead of genes names
>..... 
 ..$ ligand.complex  : chr [1:75] "F10" "F10" "F10" "F10" ...
  ..$ ligand          : chr [1:75] "F10" "F10" "F10" "F10" ...
  ..$ receptor.complex: chr [1:75] "F3" "F3" "F3" "F3" ...
  ..$ receptor        : chr [1:75] "F3" "F3" "F3" "F3" ...

Could it be because of mice "gene symbol" ? Do I need to pass through a human conversion ? Or should I just run some specify database/packages for mice  and not all of them ?

Appreciate your help
P

**Comment by dbdimitrov** [comment]
Hi @PolSabt,

You should specify the `resource` parameter to: 'MouseConsensus'. It should work then :)

**Comment by PolSabt** [comment]
Hi @dbdimitrov,

Works perfectly !

Thanks a lot :)

**Comment by trudy89** [comment]
When I run following code:
> liana_s <- liana_wrap(seurat_object, resource = "MouseConsensus")

it shows:
Expression from the `RNA` assay will be used
Running LIANA with `seurat_clusters` as labels!
Cell identities with less than 5 cells: 37 were removed!
LIANA: LR summary stats calculated!
Now Running: Natmi
Error: ℹ In index: 1.
ℹ With name: MouseConsensus.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `.f()`:
! lazy-load database '/home/dfj6357/R/x86_64-pc-linux-gnu-library/4.4/liana/R/liana.rdb' is corrupt
