### ISSUE TITLE
Omnipath error: "character" class

### ISSUE THREAD

**Issue by hzorkic** [saezlab/liana#19]
Hi! I am trying to understand why I can run 'OmniPath' alone in the wrapper, but need to put  ('OmniPath')[[1]] if I am calling a tool individually?

This works:
```
## RUN cellphoneDB alone with CellChatDB
## NOTE: CellPhoneDB will not run with OmniPath, but I am working to fix this
cpdb_res <- call_squidpy(
  seurat_object = testdata,
  op_resource = ('OmniPath')[[1]])
## Show CellPhoneDB Results
cpdb_res
```

This does not work:
```
## RUN cellphoneDB alone with CellChatDB
## NOTE: CellPhoneDB will not run with OmniPath, but I am working to fix this
cpdb_res <- call_squidpy(
  seurat_object = testdata,
  op_resource = ('OmniPath'))
## Show CellPhoneDB Results
cpdb_res
```

Thank you!

**Comment by dbdimitrov** [comment]
Hi @hzorkic,

Apologies for the delayed response as I was on holidays.

I think the inconsistency that you are referring to has now been addressed, so if you update LIANA to the latest version it should be solved - i.e. call_squidpy should run with a resource passed as a tibble as well as a list of resources. This was something specific to the Squidpy pipeline, otherwise each other tool should work with the resource passed as a tibble alone.

It is worth noting that LIANA is still being expanded and my main goal is to make it much more user-friendly than the current version, yet the overall structure should not change.

Also, you should pass `select_resource("OmniPath)[[1]]` to `op_resource` (passing it as both a 1-element list or a tibble would produce the same results).

I hope this helps.

Best wishes,
Daniel
