### ISSUE TITLE
Interpretation of NA values in squidpy and iTALK ouput

### ISSUE THREAD

**Issue by dstueckm** [saezlab/liana#20]
Hi there,

I have been running LIANA using cellchat, connectome, squidpy, and iTALK, before aggregating the results.
I've noticed that >90% of the squidpy p values are NaNs - as you've previously mentioned in https://github.com/saezlab/liana/issues/17, this could be due to zero values in gene expression. However, I have confirmed this is not the case for some interactions that receive NaN. I also do not believe it would make sense for the other methods (iTALK, CellChat, connectome) to be ranking interactions highly if there was no expression (see example below).

Are there any other explanations for why the squidpy p value would be NaN? Could these be p values of zero?

Thank you,
Daniel

![image](https://user-images.githubusercontent.com/56595424/131396037-ddc4be79-b3ad-4b07-b558-0e51665f828b.png)

**Comment by dbdimitrov** [comment]
Hi @dstueckm,

Usually most of Squidpy's pvalues are NaNs - these include interactions in which either the receptor or ligand have an expression of 0 or such that are not expressed by a given proportion of cells. 
However, based on the output you provided, I would recommend that you check what is the version of your Squidpy algorithm as version 1.0 seemed to have a bug where it would inappropriately assign NaNs to some interactions (which were indeed p-values of 0), this was later fixed in 1.1.

I hope this helps.

Regards,
Daniel

**Comment by dstueckm** [comment]
Hi Daniel,

Thanks for the response! I've updated the squidpy version in the conda environment to 1.1.0 and it's working as expected.
