### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by EJCresswell** [saezlab/liana#43]
Hi- I'm trying to install Liana into R, but I keep getting the message that it can't be installed because I can't install one of the dependencies which is now outdated and doesn't work with the latest version of R. Do you have any suggestions on how to fix this? Many thanks

Warning in install.packages :
  package ‘RobustRankAggreg’ is not available for this version of R

**Comment by dbdimitrov** [comment]
Hi @EJCresswell,

I believe it might be because they removed the package recently from CRAN.
https://cran.r-project.org/web/packages/RobustRankAggreg/index.html

Could you try installing it from here:
https://cran.r-project.org/src/contrib/Archive/RobustRankAggreg/

I will simply re-implement the algorithm in LIANA's next update and exclude it from the dependencies.

Let me know if that works.

**Comment by EJCresswell** [comment]
Hi- I tried this yesterday and it didn't work. Since updating my R and re-trying today, it seems to have worked ok. Thanks for the help :)

**Comment by dbdimitrov** [comment]
I have now re-implemented RRA and the issue should be resolved.

Feel free to re-open in case of any issues.
