### ISSUE TITLE
Issues with Visium Dataset

### ISSUE THREAD

**Issue by rishilpatel77** [saezlab/liana#60]
Hi,

We wanted to perform LIANA to look at the cell-cell communications from our spatial trancriptomics dataset, but I've ran into some trouble. Is it feasible to use LIANA for a Seurat Object using Visium? It seems like the code is mainly geared toward single-cell. Additionally, I tried running liana_wrap and ended up having all of the different slots in the object be NULL. I later tried liana_pipe with counts, and it says "Error in (function (classes, fdef, mtable)  : unable to find an inherited method for function ‘logcounts’ for signature ‘"Seurat"’". I also tried liana with 'counts' and that did not work either. I'm not sure if this is a LIANA issue or a Seurat issue.

Thanks

**Comment by dbdimitrov** [comment]
Hi @rishilpatel77,

Indeed, you could run Visium via LIANA.

 If you are using Seurat, I assume you used, SCT normalization, so I would double check if you have set `assay="SCT"` - as this would be the one that you want to pass.

> I also tried liana with 'counts' and that did not work either.
I'm not sure what you mean, sharing how you run liana and how the the object looks would help me debug a bit better.

I should also mention that in visium you will have clusters as in single-cell, but these clusters represent would typically represent niches rather than cell types/states. So, the way that you would interpret results in this case would be a bit different than in single-cell. So, whether LIANA is applicable might depend on the question that you want to address :)
