### ISSUE TITLE
CellPhoneDB cannot finish running

### ISSUE THREAD

**Issue by AltayYuzeir** [saezlab/liana#62]
Hello 
I have been experiencing some issue with the CellPhoneDB method in liana_wrap() function. It took around 2 hours to come to 100% where it got stuck for more than an hour now and does not move forward with calculating the next method. I will include a screenshot. All other methods were successfully calculated, including external ones, such as call_cellchat. I have done a conversion to mouse, using your vignette, too, if that is relevant. I tried few times, but I always had to terminate the calculation at the end.
![liana](https://user-images.githubusercontent.com/34285813/194749837-784320e1-5d21-47c3-b712-38294ed04de4.jpeg)

**Comment by dbdimitrov** [comment]
Hi @AltayYuzeir,

Your code looks good. 

Might be worth it to check how your cell types are called - i.e. do they have symbols that might be an issue. I assume since the permutations calculation goes through, the next step is a series of joins (where I assume your problem comes up).

You could also lower the number of permutations to check if this would resolve your issue by adding the following parameter:
`permutation.params = list(nperms = 100)`

Let me know if either helps.
Daniel

**Comment by AltayYuzeir** [comment]
Yes, that did it, the computation time also has dropped just to only 20 minutes
