### ISSUE TITLE
TypeError: unhashable type

### ISSUE THREAD

**Issue by wfma** [saezlab/liana#8]
I am definitely your trouble maker.

I have successfully imported the conda environment and tried to wrap my seurat obj using the liana_wrap() function. But its stuck on an error and there isnt enough info for me to figure out whats up.

The obj is just called 'stanford'

``` 
> #### Run liana ####
> liana_test <- liana_wrap(stanford,
+                          method = c('squidpy', 'connectome'),
+                          resource = c('OmniPath'))
Error: TypeError: unhashable type: 'list'
```
If you need the obj can be downloaded [here](https://drive.google.com/open?id=1cFIFOHpYKENx3sWfmRlneVXoEp3kMIIr).

**Comment by dbdimitrov** [comment]
Hi Wei,

I tried running liana on your object and noticed a couple of things that might be breaking it.

The active Ident of Seurat does not seem to match any of the columns in the metadata table (and the way that I pass the appropriate Ident to Squidpy is by matching them). I assume it might be related to the `Mø` symbol. To circumvent that you can specify the cluster keys that you wish to use the following way:

`liana_test <- liana_wrap(stanford,
                         method = c('squidpy'),
                         resource = c('OmniPath'),
                         squidpy.params = list(
                             cluster_key = "predicted.id_tabulus.sapien"
                         ))`

'squidpy.params' is a list that will be passed to Squidpy to replace the default cluster key (which is obtained via matching to the Seurat data)
Another issue was that the cluster column is possibly not a factor and I have pushed a commit that will automatically convert it to factor if needed.


Strangely, Connectome simply hangs for me with this dataset - i.e. I don't get any error. I pinpointed this to the scaleData function from Seurat, and this only happens when scaleData is called via 'exec' - very questionable?

Side note, the way that I've made exception handling in liana is that it returns any thrown exceptions in the list that it returns - this way you can inspect what went wrong with each method after the run.
 Perhaps, you could share the output list from `liana_wrap` with me and I can check what's wrong with Connectome? (Connectome is also getting re-implemented).

Thanks again,
Daniel

**Comment by wfma** [comment]
Thanks for the quick turnaround. I will run the new specified line above after I update liana. I would share the output list but when I ran it earlier it just get stuck at "Error: TypeError: unhashable type: 'list'" and R is unresponsive. I am running it in Rstudio and I cant even terminate R. I basically had to force quit Rstudio to get it to stop.

Let me run this and get back to you!
Wei

**Comment by dstueckm** [comment]
Are there any updates on the connectome issue? I tried to run liana_wrap() using 'connectome' as the only method, and I too experience infinite runtimes without any errors being thrown.
I am simply loading a Seurat object, running FindVariableFeatures() and ScaleData() before running liana_wrap(). Is scaling the data not recommended for some reason?

Also re: 'squidpy', I tried running the same script using squidpy as the method, and it returns the error "Error: attempt to select less than one element in get1index". Happy to open a separate issue for this if that's preferred, but was hoping you'd have some advice.

**Comment by dbdimitrov** [comment]
Hi dstueckm,

Thanks for the comment. 
I have now appropriately resolved the issue with Connectome.
Long story short: `exec` (or do.call) does scale well with large datasets, replacing it with `invoke` solved the issue.

Regarding, Squidpy I have not encountered that exception, perhaps opening a separate issue which I can reproduce would allow me to help you further :)

Daniel

**Comment by dstueckm** [comment]
Hi Daniel,

Thanks for the quick reply! I installed the latest version of liana and that resolved the Connectome issue. 
re: squidpy, I read your earlier comment on this post and tried converting my cell type metadata slot to a factor prior to setting the Idents() of my Seurat object, which seems to have resolved that issue.
