### ISSUE TITLE
could't able to add call_cellchat in liana_wrap

### ISSUE THREAD

**Issue by soumenbera89** [saezlab/liana#82]
Thank you so much for this nice tool. I am trying to use cellchat method using liana wrap but I getting error, although I am able to add other method. Could you please help regarding this error. I am using test data set.
> cpdb_test1 <- liana_wrap(sce,
+                         method = 'call_cellchat',
+                         resource = c("CellPhoneDB"),
+                         return_all = TRUE)
Running LIANA with `label` as labels!
Now Running: Call_cellchat
Error: :information_source: In index: 1.
:information_source: With name: CellPhoneDB.
Caused by error in `append()`:
! unused argument (return_all = return_all)

secondly, I am not able to call the function get_cellphonedb, get_cytotalk

Thank you,
Soumen.

**Comment by dbdimitrov** [comment]
Hi @soumenbera89  & @dnjst,

Indeed. This happens because this option will not work with CellChat, simply because it's being called externally.

Hmmm, allowing cellchat to `return_all` as other methods is not exactly feasible (at least not in a way that it would be consistent with the remainder of the methods).

I am considering to implement re-implement CellChat internally, but I'm concerned about it's computational speed in R. Specifically, the original CellChat implementation is in C.

I have however, implement a resource-agnostic version of CellChat in an efficient manner in [liana-py](https://github.com/saezlab/liana-py). Overall, liana-py achieves performance to which R is not even close :)

I will clarify that `return_all` is intended only for internal methods.

Thanks for using LIANA and I hope this helps!

Daniel
